//! Integration tests for validating Chat API support across different LLM providers.
//!
//! These tests read provider configurations from `config.json` (generated by
//! `cargo run --release --example export-zed-config`), spawn `nuwax-codex-acp`
//! with each provider's settings, and validate that streaming responses work.
//!
//! # Running
//!
//! ```bash
//! # Export config first (one-time):
//! cargo run --release --example export-zed-config
//!
//! # Run all provider tests (requires network + API keys):
//! cargo test --test provider_integration_test -- --ignored --test-threads=1
//!
//! # Run a specific provider:
//! cargo test --test provider_integration_test -- --ignored deepseek
//! ```

mod common;

use agent_client_protocol::schema::{
    ContentBlock, ContentChunk, InitializeRequest, NewSessionRequest, PromptRequest,
    ProtocolVersion, RequestPermissionOutcome, RequestPermissionRequest, RequestPermissionResponse,
    SelectedPermissionOutcome, SessionNotification, SessionUpdate, TextContent,
};
use agent_client_protocol::{Agent, ConnectionTo, on_receive_notification, on_receive_request};
use agent_client_protocol_tokio::AcpAgent;
use std::str::FromStr;
use std::sync::{Arc, Mutex};

/// Helper: run a single prompt against a provider and return the collected text.
async fn run_prompt(provider_name: &str, config: &common::ProviderConfig, prompt: &str) -> String {
    let agent_cmd = common::agent_command(config);
    let agent = AcpAgent::from_str(&agent_cmd).expect("Failed to parse agent command");

    let collected_text: Arc<Mutex<String>> = Arc::new(Mutex::new(String::new()));
    let collected_clone = collected_text.clone();
    let stop_reason: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));
    let stop_reason_clone = stop_reason.clone();

    let cwd = std::env::current_dir().expect("Failed to get current directory");

    eprintln!(
        "[{provider_name}] Spawning agent with model={}",
        config.model
    );

    agent_client_protocol::Client
        .builder()
        .on_receive_notification(
            async move |notification: SessionNotification, _cx| {
                match notification.update {
                    SessionUpdate::AgentMessageChunk(ContentChunk {
                        content: ContentBlock::Text(text),
                        ..
                    }) => {
                        collected_clone.lock().unwrap().push_str(&text.text);
                    }
                    SessionUpdate::ToolCall(tool_call) => {
                        eprintln!(
                            "[{provider_name}] Tool call: {} (id={})",
                            tool_call.title, tool_call.tool_call_id
                        );
                    }
                    _ => {}
                }
                Ok(())
            },
            on_receive_notification!(),
        )
        .on_receive_request(
            async move |request: RequestPermissionRequest, responder, _connection| {
                eprintln!(
                    "[{provider_name}] Auto-approving: tool_call_id={}, title={:?}",
                    request.tool_call.tool_call_id, request.tool_call.fields.title
                );
                let option_id = request.options.first().map(|opt| opt.option_id.clone());
                if let Some(id) = option_id {
                    responder.respond(RequestPermissionResponse::new(
                        RequestPermissionOutcome::Selected(SelectedPermissionOutcome::new(id)),
                    ))
                } else {
                    responder.respond(RequestPermissionResponse::new(
                        RequestPermissionOutcome::Cancelled,
                    ))
                }
            },
            on_receive_request!(),
        )
        .connect_with(agent, |connection: ConnectionTo<Agent>| async move {
            // Initialize
            connection
                .send_request(InitializeRequest::new(ProtocolVersion::V1))
                .block_task()
                .await?;

            // Create session
            let session_response = connection
                .send_request(NewSessionRequest::new(cwd))
                .block_task()
                .await?;
            let session_id = session_response.session_id;
            eprintln!("[{provider_name}] Session: {session_id}");

            // Send prompt
            let prompt_response = connection
                .send_request(PromptRequest::new(
                    session_id,
                    vec![ContentBlock::Text(TextContent::new(prompt))],
                ))
                .block_task()
                .await?;

            eprintln!(
                "[{provider_name}] Stop reason: {:?}",
                prompt_response.stop_reason
            );
            *stop_reason_clone.lock().unwrap() = Some(format!("{:?}", prompt_response.stop_reason));

            Ok(())
        })
        .await
        .expect("ACP client connection failed");

    let text = collected_text.lock().unwrap().clone();
    eprintln!("[{provider_name}] Collected {} chars of text", text.len());
    text
}

// ---------------------------------------------------------------------------
// Tests (all ignored by default — require network + API keys)
// ---------------------------------------------------------------------------

#[tokio::test]
#[ignore = "requires API key in config.json and network access"]
async fn deepseek_chat_api_basic_prompt() {
    let config = common::load_config();
    let provider = config
        .providers
        .get("deepseek")
        .expect("deepseek provider not found in config.json");

    let response = run_prompt(
        "deepseek",
        provider,
        "What is 2+2? Reply with just the answer.",
    )
    .await;

    assert!(
        !response.is_empty(),
        "DeepSeek response should not be empty"
    );
    eprintln!("DeepSeek response: {response}");
}

#[tokio::test]
#[ignore = "requires API key in config.json and network access"]
async fn glm_chat_api_basic_prompt() {
    let config = common::load_config();
    let provider = config
        .providers
        .get("glm")
        .expect("glm provider not found in config.json");

    let response = run_prompt("glm", provider, "What is 2+2? Reply with just the answer.").await;

    assert!(!response.is_empty(), "GLM response should not be empty");
    eprintln!("GLM response: {response}");
}

#[tokio::test]
#[ignore = "requires API key in config.json and network access"]
async fn minimax_chat_api_basic_prompt() {
    let config = common::load_config();
    let provider = config
        .providers
        .get("minimax")
        .expect("minimax provider not found in config.json");

    let response = run_prompt(
        "minimax",
        provider,
        "What is 2+2? Reply with just the answer.",
    )
    .await;

    assert!(!response.is_empty(), "MiniMax response should not be empty");
    eprintln!("MiniMax response: {response}");
}

#[tokio::test]
#[ignore = "requires API key in config.json and network access"]
async fn deepseek_chat_api_tool_use() {
    let config = common::load_config();
    let provider = config
        .providers
        .get("deepseek")
        .expect("deepseek provider not found in config.json");

    let response = run_prompt(
        "deepseek",
        provider,
        "Run the command 'echo hello world' and tell me what it outputs.",
    )
    .await;

    assert!(
        !response.is_empty(),
        "DeepSeek tool use response should not be empty"
    );
    eprintln!("DeepSeek tool use response: {response}");
}

#[tokio::test]
#[ignore = "requires API key in config.json and network access"]
async fn minimax_chat_api_tool_use() {
    let config = common::load_config();
    let provider = config
        .providers
        .get("minimax")
        .expect("minimax provider not found in config.json");

    let response = run_prompt(
        "minimax",
        provider,
        "Run the command 'echo hello world' and tell me what it outputs.",
    )
    .await;

    assert!(
        !response.is_empty(),
        "MiniMax tool use response should not be empty"
    );
    eprintln!("MiniMax tool use response: {response}");
}
